### ISSUE TITLE
Swap Iframe with YouTube Player API

### ISSUE THREAD

**Issue by amitness** [studenton/shuffle#15]

**Comment by kunalkakade** [comment]
Hi. I would like to work on this. I am new to opensource but i thank i can do this.

**Comment by kunalkakade** [comment]
I tried to use YouTube Player API but it didn't work.
![screenshot 14](https://user-images.githubusercontent.com/11459007/29738811-a5ca7826-8a4b-11e7-9e96-407726902add.png)

**Comment by amitness** [comment]
@kunalkakade Sure, you can.

Are other videos playing? There is a problem playing Vevo even with current version without API.

**Comment by kunalkakade** [comment]
yes other videos(which are not from vevo) are playing but most of the music videos are from vevo .

> There is a problem playing Vevo even with current version without API.

I think all the videos( with vevo) are playing perfectly on your webapp.

**Comment by amitness** [comment]
@kunalkakade I see. So, iFrame is the best approach for now. If you can find out why API is not allowing vevo videos and a workaround, we can swap.
