### ISSUE TITLE
Display Song Metadata

### ISSUE THREAD

**Issue by amitness** [studenton/shuffle#16]

**Comment by shubham76** [comment]
Hello! I was thinking about using web-scraping. We can scrap the URL of the current song and fetch all the related information. What do you think?

**Comment by amitness** [comment]
@shubham76 Yes that would work too. 

1. Another approach could be to use JS and YouTube API to get the information. 
2. Or fetching the information from the embedded iFrame using Jquery?

I've tried to make the web app to be static so that it can be hosted on GitHub pages. If scraping is possible without needing any backend, please go forward :)

**Comment by shubham76** [comment]
The first approach you suggested looks simpler. I'll give it a try.

**Comment by MatthewBurke1995** [comment]
Hey, I've got a way simple way to show the song title within the iFrame player. Is that OK or did you want the song title within header tags above the video?

**Comment by amitness** [comment]
@MatthewBurke1995 Yeah, we want the song title outside the Iframe. I'm guessing you played around with the query parameters for the Iframe.

**Comment by kiranshahi** [comment]
@amitness can I work on this issue?

**Comment by amitness** [comment]
Sure @kiranshahi

**Comment by rajalakshmi-v15** [comment]
Hi, @amitness . May I know if the issue is still unresolved? I would like to work on it. Thanks.
